version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"  # Map host port 8000 to container port 8000 (optional for external access)
    env_file:
      - .env  # Load environment variables if needed

  frontend:
    build: ./frontend
    ports:
      - "7860:7860"  # Map host port 7860 to container port 7860
    depends_on:
      - backend  # Ensures backend starts first
    env_file:
      - .env  # Load environment variables if needed
    environment:
      - BACKEND_URL=http://backend:8000  # Optional: Pass backend URL to frontend via env var